### **NumPy**

1. NumPy is a Python library for scientific computing in Python. 
2. It contains a collection of tools and techniques that can be used to solve on a computer mathematical models of problems in Science and Engineering. 
3. One of these tools is a high-performance multidimensional array object that is a powerful data structure for efficient computation of arrays and matrices. 
4. To work with these arrays, there’s a vast amount of high-level mathematical functions operate on these matrices and arrays.

In [ ]:
import numpy as np 
np.__version__

'1.21.6'

In [ ]:
# Make the array `my_array`
my_array = np.array([[1,2,3,4], [5,6,7,8]], dtype=np.int64)

# Print `my_array`
print(my_array)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
# Create an array of ones
a = np.ones((3,4))

# Create an array of zeros
b = np.zeros((2,3,4))

# Create an array with random values
c = np.random.random((2,2))

# Create an empty array
d = np.empty((3,2))

# Create a full array
e = np.full((2,2),7)

# Create an array of evenly-spaced values
f = np.arange(10,25,3)

# Create an array of evenly-spaced values
g = np.linspace(0,2,9)

In [ ]:
print(a)
print(b)
print(c)
print(d)
print(e)
print(f)
print(g)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
[[0.45514185 0.64532065]
 [0.73799193 0.44648558]]
[[2.5572806e-316 0.0000000e+000]
 [0.0000000e+000 0.0000000e+000]
 [0.0000000e+000 0.0000000e+000]]
[[7 7]
 [7 7]]
[10 13 16 19 22]
[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]


In [ ]:
# Print the number of `my_array`'s dimensions
print(a.ndim)

# Print the number of `my_array`'s elements
print(a.size)

# Print information about `my_array`'s memory layout
#print(a.flags)

# Print the length of one array element in bytes
print(a.itemsize)

# Print the total consumed bytes by `my_array`'s elements
print(a.nbytes)

2
12
8
96


In [ ]:
# Print the length of `my_array`
print(len(a))

print(a)

# Change the data type of `my_array`
a.astype(float)

3
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
# Initialize `x`
x = np.ones((3,4))

# Check shape of `x`
print(x.shape)

# Initialize `y`
y = np.random.random((3,4))
print(y)

# Check shape of `y`
print(y.shape)

# Add `x` and `y`
x + y

(3, 4)
[[0.49600737 0.55682332 0.64488    0.07123746]
 [0.47923484 0.1690564  0.82659783 0.50917673]
 [0.25502385 0.66485885 0.54735054 0.15407815]]
(3, 4)


array([[1.49600737, 1.55682332, 1.64488   , 1.07123746],
       [1.47923484, 1.1690564 , 1.82659783, 1.50917673],
       [1.25502385, 1.66485885, 1.54735054, 1.15407815]])

In [ ]:
# Broadcasting works if one dimension of one of the numpy arrays is 1

# Initialize `x`
x = np.ones((3,4))

# Check shape of `x`
print(x.shape)

# Initialize `y`
y = np.arange(4)

# Check shape of `y`
print(y.shape)

# Subtract `x` and `y`
x - y 

(3, 4)
(4,)


array([[ 1.,  0., -1., -2.],
       [ 1.,  0., -1., -2.],
       [ 1.,  0., -1., -2.]])

In [ ]:
# The shape of the resulting array will again be the maximum size along each dimension of x and y

# Initialize `x` and `y`
x = np.ones((3, 4))
#print(x)

# y = np.random.random((5, 1, 4))
y = np.random.randint(1, 100, size=(5,1,4))
print(y)

# Add `x` and `y`
z = x + y
print(z.shape)
z

[[[53 11 21 70]]

 [[57 64 52 97]]

 [[16 24 55 41]]

 [[ 6 84 43 78]]

 [[69 42 37 58]]]
(5, 3, 4)


array([[[54., 12., 22., 71.],
        [54., 12., 22., 71.],
        [54., 12., 22., 71.]],

       [[58., 65., 53., 98.],
        [58., 65., 53., 98.],
        [58., 65., 53., 98.]],

       [[17., 25., 56., 42.],
        [17., 25., 56., 42.],
        [17., 25., 56., 42.]],

       [[ 7., 85., 44., 79.],
        [ 7., 85., 44., 79.],
        [ 7., 85., 44., 79.]],

       [[70., 43., 38., 59.],
        [70., 43., 38., 59.],
        [70., 43., 38., 59.]]])

In [ ]:
# Add `x` and `y`
sum = np.add(x,y)
print(sum)

# Subtract `x` and `y`
diff = np.subtract(x,y)
print(diff)

# Multiply `x` and `y`
prod = np.multiply(x,y)
print(prod)

# Divide `x` and `y`
quo = np.divide(x,y)
print(quo)

# Calculate the remainder of `x` and `y`
rem = np.remainder(x,y)
print(rem)

In [ ]:
print(x)
print(x.min())
print(x.sum())
print(x.max(axis=0))
print(x.cumsum(axis=1))
print(x.mean())
print(np.std(a))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
1.0
12.0
[1. 1. 1. 1.]
[[1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]]
1.0
0.0


In [ ]:
# `a` AND `b` 
np.logical_and(a, b)

# `a` OR `b` 
np.logical_or(a, b)

# `a` NOT `b` 
np.logical_not(a,b)

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

## Subset, slice, index arrays

In [ ]:
# Make the array `my_array`
my_2d_array = np.array([[1,2,3,4], [5,6,7,8]], dtype=np.int64)

# Print `my_array`
print(my_2d_array)
print(my_2d_array.ndim)

[[1 2 3 4]
 [5 6 7 8]]
2


In [ ]:
my_3d_array = np.random.randint(1, 100, size=(5,2,4))
print(my_3d_array.ndim)
print(my_3d_array)

3
[[[91 79 25 50]
  [59 27  5 70]]

 [[33 52 56  7]
  [79 41 61 86]]

 [[56 25 57  9]
  [83 40 42 29]]

 [[46 71 41  4]
  [83  2  4 46]]

 [[11 27 65  8]
  [16 38 70 36]]]


In [ ]:
# Select the element at row 1 column 2
print(my_2d_array[1][2])

# Select the element at row 1 column 2
print(my_2d_array[1,2])

# Select the element at row 1, column 2 and 
print(my_3d_array[1,1,2])

7
7
61


In [ ]:
# Select items at index 0 and 1
print(my_2d_array[0:2])

# Select items at row 0 and 1, column 1
print(my_2d_array[0:2,1])

# Select items at row 1
# This is the same as saying `my_3d_array[1,:,:]
print(my_3d_array[1,...])

[[1 2 3 4]
 [5 6 7 8]]
[2 6]
[[33 52 56  7]
 [79 41 61 86]]


In [ ]:
# Try out a simple example
print(my_2d_array[my_2d_array<2])

# Specify a condition
bigger_than_3 = (my_3d_array >= 3)

# Use the condition to index our 3d array
print(my_3d_array[bigger_than_3])

[1]
[91 79 25 50 59 27  5 70 33 52 56  7 79 41 61 86 56 25 57  9 83 40 42 29
 46 71 41  4 83  4 46 11 27 65  8 16 38 70 36]


In [ ]:
print(y)
print(np.sort(y, axis = 0))
print(y.transpose())
print(y.T)

[[[53 11 21 70]]

 [[57 64 52 97]]

 [[16 24 55 41]]

 [[ 6 84 43 78]]

 [[69 42 37 58]]]
[[[ 6 11 21 41]]

 [[16 24 37 58]]

 [[53 42 43 70]]

 [[57 64 52 78]]

 [[69 84 55 97]]]
[[[53 57 16  6 69]]

 [[11 64 24 84 42]]

 [[21 52 55 43 37]]

 [[70 97 41 78 58]]]
[[[53 57 16  6 69]]

 [[11 64 24 84 42]]

 [[21 52 55 43 37]]

 [[70 97 41 78 58]]]


In [ ]:
first = np.array([1, 2, 3])
second = np.array([4, 5, 6])

import numpy.ma as ma

con = ma.concatenate([first, second])
print(con.data)

print(ma.concatenate([first, second]))

[1 2 3 4 5 6]
[1 2 3 4 5 6]


In [ ]:
square = np.array([
    [16, 3, 2, 13],
    [5, 10, 11, 8],
    [9, 6, 7, 12],
    [4, 15, 14, 1]
])

for i in range(4):
    assert square[:, i].sum() == 34
    assert square[i, :].sum() == 34


assert square[:2, :2].sum() == 34

assert square[2:, :2].sum() == 34

assert square[:2, 2:].sum() == 34

assert square[2:, 2:].sum() == 34

In [ ]:
square[2:, :2]

array([[ 9,  6],
       [ 4, 15]])

In [ ]:
numbers = np.linspace(5, 50, 24, dtype=int).reshape(4, -1)

numbers

array([[ 5,  6,  8, 10, 12, 14],
       [16, 18, 20, 22, 24, 26],
       [28, 30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48, 50]])

In [ ]:
mask = numbers % 4 == 0
mask

array([[False, False,  True, False,  True, False],
       [ True, False,  True, False,  True, False],
       [ True, False,  True, False,  True, False],
       [ True, False,  True, False,  True, False]])

In [ ]:
numbers[mask]

array([ 8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48])

In [ ]:
by_four = numbers[numbers % 4 == 0]

In [ ]:
from numpy.random import default_rng

rng = default_rng()

In [ ]:
values = rng.standard_normal(10000)

In [ ]:
values[:5]

array([ 2.81507517, -0.1313348 , -0.45806688,  0.32963905,  0.62134456])

In [ ]:
std = values.std()
std

1.0016759064484266

In [ ]:
filtered = values[(values > -2 * std) & (values < 2 * std)]

In [ ]:
filtered.size / values.size

0.954

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [ ]:
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 3)

print(newarr[0])
print(newarr[1])
print(newarr[2])


[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[ 9 10]
 [11 12]]


In [ ]:
# split along rows

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3, axis=1)
# newarr = np.array_split(arr, 3)

print(arr)
print(newarr[0])
print(newarr[1])
print(newarr[2])


In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.hsplit(arr, 3)

print(newarr[0])
print(newarr[1])
print(newarr[2])


In [ ]:
## JOIN

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [ ]:
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)

print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [ ]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [ ]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))

print(arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))

print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


In [ ]:
a = np.array([[1,2],[3,4]]) 
b = np.array([[11,12],[13,14]]) 
np.dot(a,b)

# [[1*11+2*13, 1*12+2*14],[3*11+4*13, 3*12+4*14]]

array([[37, 40],
       [85, 92]])

In [ ]:
a = np.array([[1,2],[3,4]]) 
b = np.array([[11,12],[13,14]]) 
np.vdot(a,b)

# 1*11 + 2*12 + 3*13 + 4*14 = 130

130

Bit-wise ops

In [ ]:
a,b = 13,17 
print(bin(a))
print(bin(b))

print(np.bitwise_and(13, 17))

b1101
0b10001


NameError: ignored

In [ ]:
np.bitwise_or(13, 17)

29

In [ ]:
np.invert(np.array([13], dtype = np.uint8)) 
np.binary_repr(13, width = 8) 
np.binary_repr(242, width = 8)

'11110010'

In [ ]:
print('Left shift of 10 by two positions:' )
print(np.left_shift(10,2) )


print('Binary representation of 10:' )
print(np.binary_repr(10, width = 8) )
 

print('Binary representation of 40:' )
np.binary_repr(40, width = 8)  

Left shift of 10 by two positions:
40
Binary representation of 10:
00001010
Binary representation of 40:


'00101000'

In [ ]:
print('Left shift of 10 by two positions:' )
print(np.right_shift(40,2) )


print('Binary representation of 10:' )
print(np.binary_repr(40, width = 8) )
 

print('Binary representation of 40:' )
np.binary_repr(10, width = 8)  

Left shift of 10 by two positions:
10
Binary representation of 10:
00101000
Binary representation of 40:


'00001010'

In [ ]:
print('Concatenate two strings:' )
print(np.char.add(['hello'],[' xyz']) )

print('Concatenation example:' )
print(np.char.add(['hello', 'hi'],[' abc', ' xyz']))

Concatenate two strings:
['hello xyz']
Concatenation example:
['hello abc' 'hi xyz']


In [ ]:
np.char.multiply('Hello ',3)

array('Hello Hello Hello ', dtype='<U18')

In [ ]:
np.char.center('hello', 20, fillchar = '*')

array('*******hello********', dtype='<U20')

In [ ]:
np.char.capitalize('hello world')

array('Hello world', dtype='<U11')

In [ ]:
np.char.title('hello how are you?')

array('Hello How Are You?', dtype='<U18')

In [ ]:
np.char.lower(['HELLO','WORLD']) 

array(['hello', 'world'], dtype='<U5')

In [ ]:
np.char.upper('hello') 

array('HELLO', dtype='<U5')

In [ ]:
print(np.char.split ('hello how are you?') )
print(np.char.split ('TutorialsPoint, Hyderabad, Telangana', sep = ','))

['hello', 'how', 'are', 'you?']
['TutorialsPoint', ' Hyderabad', ' Telangana']


In [ ]:
print(np.char.splitlines('hello\nhow are you?') )
print(np.char.splitlines('hello\rhow are you?'))

#This function returns a list of elements in the array, breaking at line boundaries.

['hello', 'how are you?']
['hello', 'how are you?']


In [ ]:
print(np.char.strip('ashok arora','a') )
print(np.char.strip(['arora','admin','java'],'a'))

#This function returns a copy of array with elements stripped of the specified characters leading and/or trailing in it.

shok aror
['ror' 'dmin' 'jav']


In [ ]:
print(np.char.join(':','dmy') )
print(np.char.join([':','-'],['dmy','ymd']))

d:m:y
['d:m:y' 'y-m-d']


In [ ]:
np.char.replace ('He is a good boy', 'is', 'was')

array('He was a good boy', dtype='<U17')

Resources:

https://www.geeksforgeeks.org/numpy-tutorial/

https://realpython.com/numpy-tutorial/

## Time for practice few questions!

Q1. Faltten the following array.

A. [[1,2,3],
[4,5,6],
[7,8,9]]

B.e

Q2. What will the output of the following code and explain the code with proper comments.

```
import numpy as np

arr = []
temp = []

for i in range(12):
    temp.append(np.random.rand()*10)
    if((len(temp)) % 3 == 0):
        arr.append(temp)
        temp = []
        
arr =  np.array(arr)
print(arr.flatten())
print(arr)
```




In [ ]:
# Copy paste your ans in string format in print function below
print()

print()

In [ ]:
# Do proper commenting
import numpy as np

arr = []
temp = []

for i in range(12):
    temp.append(np.random.rand()*10)
    if((len(temp)) % 3 == 0):
        arr.append(temp)
        temp = []

arr =  np.array(arr)
print(arr.flatten())
print(arr)

Q3. Explain the difference between the following and when they are used? 

A. np.identity() and np.eye() 

B. np.zeros() and np.ones()

C. np.random.randint() and np.random.rand()

In [ ]:
# write your answers in below print statement in form of string

print()

print()

print()

Q4. What will be the output of the following code?

```
import numpy as np

a = np.array( [[21,15, 19, 18, 17],[16, 20, 14, 13, 12], [11, 10 , 9 , 8 , 7], [6 , 5,  4,  3,  2]])
b = a[:,1]
b = sorted(b)
c = a.copy()
k = 0
for i in b:
    index = np.where(a[:,1] == i)
    c[k] = a[index]
    k+=1
    
print(c)
```



In [ ]:
# print the output in the form of string.
print()