# <center> Starting with Semantic Segmentation

# <center> Transpose Convolution

#### Transposed Convolutions are used to upsample the input feature map to a desired output feature map using some learnable parameters.



## Why do we need transpose convolution?




One of the best ways for us to gain some intuition is by looking at examples from Computer Vision that use the transposed convolution. Most of these examples start with a series of regular convolutions to compress the input data into an abstract spatial representation, and then use transposed convolutions to decompress the abstract representation into something of use.


![](https://miro.medium.com/max/1400/1*1OabPemOWCLrpCwIUmIsCg.png)


A convolutional auto-encoder is tasked with recreating its input image, after passing intermediate results through a ‘bottleneck’ of a limited size. Uses of auto-encoders include compression, noise removal, colourisation and in-painting. Success depends on being able to learn dataset specific compression in the convolution kernels and dataset specific decompression in the transposed convolution kernels. Why stop there though?


## Super Resolution
![](https://miro.medium.com/max/1400/1*eTMo62iQxKp9aR3b5iG14w.png)


With ‘super resolution’ the objective is to upscale the input image to higher resolutions, so transposed convolutions can be used as an alternative to classical methods such as bicubic interpolation. Similar arguments to convolutions using learnable kernels over hand crafted kernels apply here.

## Semantic Segmentation


Semantic segmentation is an example of using transposed convolution layers to decompress the abstract representation into a different domain (from the RGB image input). We output a class for each pixel of the input image, and then just for visualisation purposes, we render each class as a distinct colour (e.g. the person class shown in red, cars in dark blue, etc.).


![](https://miro.medium.com/max/1400/1*KICInky28yGdU9T45kIL5Q.jpeg)

1. The CNN layers we have seen so far, such as convolutional layers and pooling layers typically reduce (downsample) the spatial dimensions (height and width) of the input, or keep them unchanged. 

2. In semantic segmentation that classifies at pixel-level, it will be convenient if the spatial dimensions of the input and output are the same. For example, the channel dimension at one output pixel can hold the classification results for the input pixel at the same spatial position.

3. To achieve this, especially after the spatial dimensions are reduced by CNN layers, we can use another type of CNN layers that can increase (upsample) the spatial dimensions of intermediate feature maps. 

4. In this session, we will introduce transposed convolution, which is also called fractionally-strided convolution, for reversing downsampling operations by the convolution.

# Now let's understand how transpose convolution works 



### The basic operation that goes in a transposed convolution is explained below:
### 1. Consider a 2x2 encoded feature map which needs to be upsampled to a 3x3 feature map

![](https://miro.medium.com/max/97/1*BMJnnOKPhK8hoFP6sQ9edQ.png) 

Input Feature map

![](https://miro.medium.com/max/252/1*VxtMdM-DsGwIa51GyDx-XQ.png)

Output feature shape





### 2. We take a kernel of size 2x2 with unit stride and zero padding.

![](https://miro.medium.com/max/102/1*e6UnrcsFRaOidCq7mwJpTA.png)

kernel of size 2*2

### 3. Now we take the upper left element of the input feature map and multiply it with every element of the kernel

![](https://miro.medium.com/max/429/1*7hVid7EAqCPkG6sEjHMI5w.png)



### 4. Similarly, we do it for all the remaining elements of the input feature map

![](https://miro.medium.com/max/700/1*yxBd_pCiEVVwEQFmc-Heog.png)

### 5. As you can see, some of the elements of the resulting upsampled feature maps are over-lapping. To solve this issue, we simply add the elements of the over-lapping positions

![](https://miro.medium.com/max/700/1*faRskFzI7GtvNCLNeCN8cg.png)




## 6. The resulting output will be the final upsampled feature map having the required spatial dimensions of 3x3

![](https://miro.medium.com/max/790/1*Lpn4nag_KRMfGkx1k6bV-g.gif)

In [ ]:
def trans_conv(X, K):
    h, w = K.shape
    Y = np.zeros((X.shape[0] + h - 1, X.shape[1] + w - 1))
    for i in range(X.shape[0]):
        for j in range(X.shape[1]):
            
    return Y

In [ ]:
import numpy as np
X = np.array()
K = np.array()
trans_conv(X, K)

array([[ 0.,  0.,  1.],
       [ 0.,  4.,  6.],
       [ 4., 12.,  9.]])

## Experimenting with Transpose convolution with tensorflow

In [ ]:
import tensorflow as tf

In [ ]:
kz = 2 # kernel_size
st = 1 # strides

input = tf.random.uniform((1, 2, 2, 2)) #batch size, width, height, channels

trans_conv1 = 

output = trans_conv1(input)

print(output)


tf.Tensor(
[[[[-0.03889751  0.15880191 -0.6228331 ]
   [ 0.59077346  0.27995276  0.1568805 ]
   [ 0.20918417  0.1426722   0.20924921]]

  [[ 0.7025579  -0.33298817 -1.0997314 ]
   [ 0.7622224   0.11959708  0.27228004]
   [ 0.35491088  0.02095272  0.41483644]]

  [[ 0.39930668 -0.00877144 -0.33141065]
   [ 0.21797168 -0.7138029  -0.05770034]
   [ 0.0172114  -0.2627305   0.17915061]]]], shape=(1, 3, 3, 3), dtype=float32)


In [ ]:
kz = 3 # kernel_size
st = 1 # strides

input = tf.random.uniform((1, 2, 2, 2)) #batch size, width, height, channels

trans_conv1 = 

output = trans_conv1(input)

print(output)

tf.Tensor(
[[[[-0.11209656 -0.27499148 -0.13187832]
   [ 0.10768551 -0.4161841   0.06970149]
   [-0.21159905 -0.41713256  0.36059037]
   [-0.03529995 -0.04829163  0.03959601]]

  [[-0.575434   -0.25036544  0.14100556]
   [-0.11381018 -0.33323848 -0.37841514]
   [-0.09271055 -0.44242233  0.55248183]
   [-0.25185734 -0.42277905  0.4132728 ]]

  [[-0.41210997 -0.21410598  0.17040288]
   [-0.5856804   0.5106653   0.0050596 ]
   [ 0.22441702  0.49383527 -0.03997694]
   [ 0.165867    0.16605446  0.35261524]]

  [[-0.05118412 -0.02201918 -0.05709676]
   [ 0.06698136  0.10163553  0.22887588]
   [ 0.40975782  0.04867091 -0.11633299]
   [ 0.22611399  0.21017109  0.27243763]]]], shape=(1, 4, 4, 3), dtype=float32)


In [ ]:
kz = 3 # kernel_size
st = 2 # strides

input = tf.random.uniform((1, 2, 2, 2)) #batch size, width, height, channels

trans_conv1 = tf.keras.layers.Conv2DTranspose(filters = 3, kernel_size = kz, strides= st , padding='valid')

output = trans_conv1(input)

print(output)

tf.Tensor(
[[[[-2.55586624e-01 -1.87857181e-01 -1.40791982e-01]
   [ 2.38769889e-01 -1.12117015e-01 -4.34987955e-02]
   [-4.63412791e-01 -3.54007244e-01 -2.52539635e-01]
   [ 3.00569057e-01 -2.13020876e-01  7.98673704e-02]
   [-9.44526270e-02 -1.09445848e-01  1.04657494e-01]]

  [[ 1.15001284e-01  9.94654670e-02  7.74565265e-02]
   [-2.60280743e-02 -1.73205614e-01 -6.54332787e-02]
   [ 1.24085873e-01  3.71668667e-01  8.76246169e-02]
   [-3.08722607e-03 -1.86397448e-01  6.26173392e-02]
   [ 7.93697983e-02  2.69464254e-01  5.61633855e-02]]

  [[-4.39700216e-01 -6.17476761e-01 -6.10527247e-02]
   [ 3.74516696e-01 -2.21871972e-01 -1.57265551e-02]
   [ 2.46817470e-02 -3.58934373e-01  2.20224723e-01]
   [ 2.27812588e-01 -1.49999753e-01 -1.61039457e-01]
   [ 3.20491612e-01  1.52359590e-01  2.95387749e-02]]

  [[ 2.08820581e-01  1.95154816e-01  1.32111773e-01]
   [-3.72059904e-02 -2.96601921e-01 -7.27361217e-02]
   [ 2.94942670e-02  3.80933464e-01  6.88693076e-02]
   [-1.66558251e-02 -9.770397

## Difference between Conv2DTranspose and UpSampling2D in keras

Transpose: https://keras.io/api/layers/convolution_layers/convolution2d_transpose/

UpSampling: https://keras.io/api/layers/reshaping_layers/up_sampling2d/

In [ ]:
# Reference: https://www.matthewzeiler.com/mattzeiler/deconvolutionalnetworks.pdf